### ISSUE TITLE
Site in github repo description is a 404

### ISSUE THREAD

**Issue by kumar303** [BladeRunnerJS/topiarist#22]
This github repo's description reads:

Topiarist provides tree and shape-based type verification for JavaScript. http://bladerunnerjs.github.io/topiarist

The link to the site is a 404 for me.

**Comment by leggetter** [comment]
Looks like the `gh-pages` branch has been deleted.

**Comment by dchambers** [comment]
Thanks @kumar303, I've just removed the site link since we're now just using the plain `REAME.md` for documentation.

**Comment by dchambers** [comment]
Oh, thanks @leggetter too :smile:
